# Generated by Django 4.2.7 on 2024-02-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='car',
            new_name='post',
        ),
    ]
